opt_in_rules: 
  - empty_count
  - sorted_imports
  - force_unwrapping
  - operator_usage_whitespace
  - number_separator
  - switch_case_on_newline
  - implicit_return
  - overridden_super_call
  - object_literal
  - nimble_operator
  - first_where
  - closure_spacing
  - closure_end_indentation
  - attributes
  - explicit_init
  - explicit_type_interface
  - fatal_error_message
  - redundant_nil_coalescing
  - private_outlet
  - no_extension_access_modifier
  - conditional_returns_on_newline
  - prohibited_super_call
  - implicitly_unwrapped_optional
included:
  - Sources
  - Tests
excluded: 
  - Pods
  - Tests/Mocks

variable_name:
  min_length: 2
