osx_image: xcode8.3
language: objective-c
rvm:
 - 2.2
podfile: Podfile
before_install:
 - bundle install
 - pod repo update
 - pod install
script:
 - set -o pipefail && xcodebuild test -workspace ELDebate.xcworkspace -scheme ELDebate -sdk iphonesimulator10.3 -destination 'name=iPhone SE,OS=10.3' ONLY_ACTIVE_ARCH=NO | xcpretty
 - set -o pipefail && xcodebuild test -workspace ELDebate.xcworkspace -scheme FeatureTests -sdk iphonesimulator10.3 -destination 'name=iPhone SE,OS=10.3' ONLY_ACTIVE_ARCH=NO | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - fastlane ios autodeploy
