osx_image: xcode9
language: objective-c
rvm:
- 2.4.1
podfile: Podfile
before_install:
- openssl aes-256-cbc -K $encrypted_bbdbf7e1c4b4_key -iv $encrypted_bbdbf7e1c4b4_iv -in .setup_travis_deployment.sh.enc -out setup_travis_deployment.sh -d
- chmod +x setup_travis_deployment.sh
- . ./setup_travis_deployment.sh
- bundle install
- pod repo update
- pod install
script:
- set -o pipefail && xcodebuild test -workspace ELDebate.xcworkspace -scheme ELDebate -sdk iphonesimulator11.0 -destination 'name=iPhone SE,OS=11.0' -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES | xcpretty
- set -o pipefail && xcodebuild test -workspace ELDebate.xcworkspace -scheme FeatureTests -sdk iphonesimulator11.0 -destination 'name=iPhone SE,OS=11.0' -enableCodeCoverage NO ONLY_ACTIVE_ARCH=YES | xcpretty
- bundle exec danger
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'ELDebateFramework'
- fastlane ios autodeploy
